#! /bin/sh

while [ $# -gt 0 ]
do
	filelist=""
	case "$1" in
		prefs)
			for app in Finder QuickSilver Preview iTerm Skim Snes9x Transmission; do
				filelist="$filelist prefs/$(bid ${app}).plist"
			done
			filelist="$filelist prefs/com.apple.symbolichotkeys.plist prefs/pbs.plist prefs/fs-uae prefs/nsmb.conf"
			;;
		support)
			filelist="support/Quicksilver"
			;;
		services)
			filelist="Library/Services"
			;;
		dots)
			filelist=".coordinates .github_api_token .mpoprc .msmtprc .procmailrc .eatrc .castgetrc .npmrc"
			;;
		dirs)
			filelist=".local .config .pandoc .mutt .vim .mpd .themes .fonts .icons .aria2 .irssi .pal .FontForge .ssh .w3m .elinks .lftp .ncmpcpp .audacity-data .audacity-files"
			;;
		usenet)
			filelist=".jnewsrc .usenet_id .usenet .slrn"
			;;
		mail)
			filelist=".maildir"
			;;
		src)
			filelist="src/lang"
			;;
		abs)
			filelist="src/abs"
			;;
		doc)
			filelist="doc"
			;;
		sys)
			filelist="/etc/hooks.d"
			;;
	esac
	if [ -n "$filelist" ] ; then
		tar -cv -C "$HOME" -f "${1}.tar" $filelist
	fi
	shift
done
