#! /bin/sh

PATH="/usr/local/bin:${PATH}"
pdir=$(Z proj col | head -n 1)
LF="
"

pgrep -x mongod > /dev/null 2>&1 || mongod -f /usr/local/etc/mongod.conf
tmux rename-window tmp
tmux new-window -n msg "m" \; split-window -hd -c "#{pane_current_path}" "nb"
tmux set-buffer "j${LF}r" \; paste-buffer -t msg.2 \; delete-buffer
tmux new-window -c "${pdir}"/server -n watch "nodemon -i public"\; split-window -h -c "${pdir}" "gulp watch"
tmux new-window -c "${pdir}" -n js "e -O2 \$(v -s atime -l proj col .js | tail -r -n 6)"
tmux new-window -c "${pdir}" -n less "e -O3 \$(v -s atime -l proj col .less | tail -r -n 6)"
tmux select-window -t js
tmux kill-window -t tmp
