#! /bin/sh

# gphoto2 --get-all-files 2> /dev/null

VOLUME=${1:-"Untitled"}
DEST="$HOME/art/raw/$(date +%Y%m%d)"

[ -d "$DEST" ] || mkdir "$DEST"

find -E /Volumes/"$VOLUME" -iregex '.*\.(jpg|raf|mp4)' \
     -exec cp -v {} "$DEST" \; && chmod 644 "$DEST"/*.*

diskutil unmount "$VOLUME"
