#! /bin/sh

# gphoto2 --get-all-files 2> /dev/null

volume=${1:-"Untitled"}
base=${2:-"$HOME/art/raw"}
dest="${base}/$(date +%Y%m%d)"

[ -d "$dest" ] || mkdir "$dest"

find -E /Volumes/"$volume" -iregex '.*\.(jpg|raf|mp4)' \
     -exec cp -v {} "$dest" \; && chmod 644 "$dest"/*.*

diskutil unmount "$volume"
