#! /usr/bin/env python3

import sys
import re
from colormath.color_objects import HSLColor, sRGBColor
from colormath.color_conversions import convert_color

palette = []
args = sys.argv[1:]

if len(args) > 0:
    palette.extend(args)
else:
    for line in sys.stdin:
        color_codes = re.findall("#[0-9A-F]{6}", line, flags=re.IGNORECASE)
        palette.extend(color_codes)

if len(palette) < 1:
    print("No color found.", file=sys.stderr)
    sys.exit(1)

for c in palette:
    rgb = sRGBColor.new_from_rgb_hex(c)
    hsl = convert_color(rgb, HSLColor)
    print("{} {} {}".format(*hsl.get_value_tuple()))
