#! /usr/bin/env python3

import sys
from PIL import Image
from colormath.color_objects import sRGBColor

def get_hex(pixel):
    rgb_color = sRGBColor(*pixel, is_upscaled=True)
    return rgb_color.get_rgb_hex()

args = sys.argv[1:]

for filename in args:
    try:
        source = Image.open(filename)
    except IOError:
        print("Can't open image.", file=sys.stderr)
        sys.exit(1)

    source = source.convert('RGB')
    source_data = list(source.getdata())

    for pixel in source_data:
        hex_color = get_hex(pixel)
        print(hex_color)
