#! /bin/sh

URL_DB="$XDG_DATA_HOME"/urls.json
verb=$1
shift

case "$verb" in
	add)
		fdb -i "$URL_DB" -u -a "$@" ;;
	rm|remove)
		fdb -i "$URL_DB" -d "$@" ;;
	ls|list)
		fdb -i "$URL_DB" -q "(?i)$@" | tail -r;;
	*)
		exit 1 ;;
esac
