#! /bin/sh

URL_DB="$SHARE_ROOT"/urls.Z
verb=$1
shift

case "$verb" in
	add)
		Z -i "$URL_DB" -a "$@" ;;
	rm|remove)
		Z -i "$URL_DB" -d "$@" ;;
	ls|list)
		Z -i "$URL_DB" "$@";;
	*)
		exit 1 ;;
esac
