#! /usr/bin/env python3

import sys
import re
from colormath.color_objects import sRGBColor, LCHabColor
from colormath.color_conversions import convert_color

lch = map(lambda x: float(x), sys.argv[1:])

lch_color = LCHabColor(*lch)
rgb_color = convert_color(lch_color, sRGBColor)
hex_color = rgb_color.get_rgb_hex()

print(hex_color)
