#! /usr/bin/env node

var fs = require("fs"),
	spawn = require("child_process").spawn,
	args = process.argv.slice(2);

if (args.length < 1) {
	process.exit(1);
}

args.forEach(function (fileName) {
	var htmlFileName = fileName + ".html",
		vim = spawn("vim", ["-c", "let g:html_expand_tabs = 0 | run syntax/2html.vim | wqa", fileName]);
	vim.on("close", function (code) {
		if (code !== 0) {
			process.exit(1);
		}
		var data = fs.readFileSync(htmlFileName, "utf8");
		fs.unlinkSync(htmlFileName);
		data = data.replace(/[^]*<pre\s[^>]+>\n([^]*)<\/pre>[^]*/, "$1");
		data = data.replace(/<span\s+class="([^"]+)">([^<]+)<\/span>/g, function (match, p1, p2) {
			return "%{" + p1 + "}(" + p2.replace(/\)/g, "&rpar;") + ")";
		});
		var previewFileName = fileName + ".preview";
		console.log(previewFileName);
		fs.writeFileSync(previewFileName, data);
	});
});
