#! /bin/sh

PRG=gvim

while [ $# -gt 0 ] ; do
	case "$1" in
		*256*)
			PRG=vim ;;
		*)
			PRG=gvim ;;
	esac
	$PRG -u NONE -U NONE -c "syntax on | source ${1} | exec \"redir! > \" . g:colors_name . \".vimTheme | hi | redir END\" | quit"
	shift
done
