#! /bin/sh

PRG=gvim
INIT=""

while getopts "ld" opt ; do
    case $opt in
        l)
            INIT=" set bg=light |"
            ;;
        d)
            INIT=" set bg=dark |"
            ;;
    esac
done

shift $((OPTIND - 1))

while [ $# -gt 0 ] ; do
	case "$1" in
		*256*)
			PRG=vim ;;
		*)
			PRG=gvim ;;
	esac
	$PRG -u NONE -U NONE -c "syntax on |${INIT} source ${1} | exec \"redir! > \" . g:colors_name . \".vimTheme | hi | redir END\" | quit"
	shift
done
