#! /bin/sh

TEMPLATES_DIR="$XDG_DOTFILES_DIR/templates"
COLOR_SCHEMES_DIR="$XDG_DOTFILES_DIR/color_schemes"
OUTPUT_DIR=$(mktemp -d /tmp/colors.XXXX)

trtpl -s '-dark' -i LCH -c "${COLOR_SCHEMES_DIR}/current-dark" -o "$OUTPUT_DIR" "${TEMPLATES_DIR}/hybrid"
trtpl -s '-light' -i LCH -c "${COLOR_SCHEMES_DIR}/current-light" -o "$OUTPUT_DIR" "${TEMPLATES_DIR}/hybrid"
trtpl -c "${COLOR_SCHEMES_DIR}/current-symbolic" -o "$OUTPUT_DIR" "${TEMPLATES_DIR}/symbolic"

cp -R "${OUTPUT_DIR}"/dotfiles/* "$XDG_DOTFILES_DIR"
