#! /usr/bin/env dash

for itm in *
do
    if [ -h "$itm" ]
    then
        target=$(readlink -n "$itm")
        if [ ! -e "$target" ]
        then
            echo "$itm -/-> $target"
            rm "$itm"
        fi
    fi
done
