#! /usr/bin/env python3

import sys
import re
from colormath.color_objects import sRGBColor, LCHabColor
from colormath.color_conversions import convert_color

palette = []
args = sys.argv[1:]

if len(args) > 0:
    palette.append(" ".join(args))
else:
    for line in sys.stdin:
        colors = re.findall("\d+\s+\d+\s+\d+", line)
        palette.extend(colors)

if len(palette) < 1:
    print("No color found.", file=sys.stderr)
    sys.exit(1)

for color in palette:
    rgb = map(int, re.split("\s+", color))
    rgb_color = sRGBColor(*rgb, is_upscaled=True)
    lch_color = convert_color(rgb_color, LCHabColor)
    print("{} {} {}".format(*lch_color.get_value_tuple()))
