#! /bin/sh

dst=/mnt/livebox/data
trg=$(hostname -s)
cmd=$1
shift

case "$cmd" in
	ls)
		pax -f "${dst}/${1:-$trg}.pax" 2> /dev/null ;;
	list)
		pax -v -f "${dst}/${1:-$trg}.pax" 2> /dev/null ;;
	scan)
		{ cd "$dst" && ls *.pax; } 2> /dev/null ;;
	pack|packto)
		if [ "$cmd" = "packto" ] ; then
			trg=$1
			shift
		fi
		opt="-w"
		[ -e "${dst}/${trg}.pax" ] && opt="$opt -au"
		pax -L -v $opt -f "${dst}/${trg}.pax" "$@" ;;
	unpack)
		arg=$1
		shift
		pax -v -ru -f "${dst}/${arg}.pax" "$@" ;;
	rm|remove)
		rm -v "${dst}/${1:-$trg}.pax" 2> /dev/null ;;
	*)
		exit 1 ;;
esac
