#! /bin/sh

dst=/mnt/livebox/data
trg=$(hostname -s)
cmd=$1
shift

case "$cmd" in
	ls)
		pax -f "$dst/${1:-$trg}.pax" 2> /dev/null ;;
	list)
		pax -v -f "$dst/${1:-$trg}.pax" 2> /dev/null ;;
	pack)
		opt="-w"
		[ -e "$dst/${trg}.pax" ] && opt="$opt -au"
		pax -v $opt -f "$dst/${trg}.pax" "$@" ;;
	unpack)
		arg=$1
		shift
		pax -v -ru -f "$dst/${arg}.pax" "$@" ;;
	destroy)
		rm -v "$dst/${1:-$trg}.pax" 2> /dev/null ;;
esac
