#! /usr/bin/env python3

# Remove ads from SNCF tickets

import sys
from getopt import getopt

start_index = 11
stop_index = 17

options, args = getopt(sys.argv[1:], 'i:I:')
for opt, val in options:
    if opt == '-i':
        start_index = int(val)
    elif opt == '-I':
        stop_index = int(val)

for filename in args:
    with open(filename, 'rb') as input:
        with open('output_{}'.format(filename), 'wb') as output:
            pos = 0
            for line in input:
                if line.find(b'/Subtype /Image') != -1:
                    pos = pos + 1
                    if pos > start_index and pos < stop_index:
                        line = line.replace(b'/Subtype /Image', b'/Subtype /Foo')
                output.write(line)
