#! /bin/bash

declare -a args

while getopts "e:" opt ; do
	case $opt in
		e)
			args+=("--exclude" "$OPTARG")
			;;
	esac
done

shift $((OPTIND - 1))

name=$1
shift

tar -cvz "${args[@]}" -f "${name}.tgz" "$@"
