#! /bin/sh

exclude=

while getopts "e:" opt ; do
    case $opt in
        e)
            exclude="$OPTARG"
            ;;
    esac
done

shift $((OPTIND - 1))

name=$1
shift

tar -cvz --exclude "$exclude" -f "${name}.tgz" "$@"
