#! /usr/bin/env dash

if [ $# -gt 0 ] ; then
    bgtype=$1
else
	bgtype=$(cat "$HOME"/.conditions)
    case "$bgtype" in
        Dark)
            bgtype=Light
            ;;
        Light)
            bgtype=Dark
            ;;
    esac
fi

printf "%s" "$bgtype" > "$HOME"/.conditions
osascript - << END
tell application "Terminal"
	set default settings to settings set "Hemisu $bgtype"
	set current settings of tabs of windows to settings set "Hemisu $bgtype"
end tell
END
