#! /bin/sh

PATH="/usr/local/bin:${PATH}"

curbg=$(cat "$BGTYPE")

if [ $# -gt 0 ] ; then
	nextbg=$1
else
	case "$curbg" in
		light)
			nextbg=dark
			itermkey="("
			;;
		dark)
			nextbg=light
			itermkey=")"
			;;
	esac
fi

printf "%s" "$nextbg" > "$BGTYPE"

osascript -e 'tell application "System Events" to keystroke "'$itermkey'" using {command down,control down}'

if [ "$nextbg" != "$curbg" ] ; then
	echo ":source ~/.vimrc" | tmux load-buffer -
	for sess in $(tmux list-sessions -F "#{session_id}") ; do
		for win in $(tmux list-windows -t "$sess" -F "#{window_id}") ; do
			for pane_pid in $(tmux list-panes -t "$win" -F "#{pane_id},#{pane_pid}") ; do
				pane=${pane_pid%,*}
				pid=${pane_pid#*,}
				while [ -n "$pid" ] ; do
					if pgrep -P $pid -x vim > /dev/null ; then
						tmux paste-buffer -t "$pane"
						pid=""
					else
						pid=$(pgrep -P $pid -n)
					fi
				done
			done
		done
	done
fi
