#! /bin/sh

base=output

while getopts 'b:' opt ; do
    case $opt in
        b)
            base=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

cnt=1
input=$1
shift
ext=${input##*.}

while [ $# -gt 0 ] ; do
    begin=$1
    shift
    end=$1
    ffmpeg -i "$input" -c copy -ss "$begin" -to "$end" "${base}-$(printf '%03d' $cnt).$ext"
    shift
    cnt=$((cnt + 1))
done
