#! /bin/sh

ext=${1##*.}
lst=$(mktemp /tmp/video.XXXX)

while [ $# -gt 0 ] ; do
    printf "file '%s'\n" "$PWD"/"$1" >> "$lst"
    shift
done

ffmpeg -f concat -i "$lst" -c copy "output.$ext"

rm "$lst"
