#! /bin/sh

args=$@
WEATHER_LOCATION=${args:-$WEATHER_CODE}
METRIC_URL_SUFFIX="&u=c"
bold=$(printf '\033[1;39m')
blue=$(printf '\033[1;34m')
magenta=$(printf '\033[1;35m')
reset=$(printf '\033[0m')

answer=$(wget -o /dev/null -qO - "http://xml.weather.yahoo.com/forecastrss?p=${WEATHER_LOCATION}${METRIC_URL_SUFFIX}" | sed -En 's/.*- ([^\.]+)\. High: (-?[0-9]+) Low: (-?[0-9]+).*/\1 \3 \2/p')

[ -t 1 ] && answer=$(printf "%s" "$answer" | sed -E 's/(.*) (-?[0-9]+) (-?[0-9]+)/'${bold}'\1 '${blue}'\2 '${magenta}'\3'${reset}'/')

printf "%s\n" "$answer"
